# ==============================================================================
# Environment setup
# ==============================================================================
image: server-harbor:80/dls2/dls2-dev:latest

# ==============================================================================
# Stages
# ==============================================================================
stages:
   - preamble
   - build
   - deploy

before_script:
  - source /root/dls_gitlab_ci/gitlab-script.sh
  - sudo apt-get update
  - sudo apt-get install -y dls2-dev

# ------------------------------------------------------------------------------
# Preamble Stage
# ------------------------------------------------------------------------------
# Print versions of installed programmes on the docker image. 
# This is helpful for a quick sanity check when things break
preamble:
  stage: preamble
  tags:
    - dls2
  script:
    - source /root/dls_gitlab_ci/gitlab-preamble.sh
  artifacts:
    paths:
      - version
      - release

# ------------------------------------------------------------------------------
# Build Stage
# ------------------------------------------------------------------------------
build-and-test:
  stage: build
  tags:
    - dls2
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
  artifacts:
    paths:
      - build/*
      - bin/*
    expire_in: 3 hrs

# ------------------------------------------------------------------------------
# Deploy Stage
# ------------------------------------------------------------------------------
deploy:
  stage: deploy
  tags:
    - dls2
  script:
    - cd build
    - make package
    - source /root/dls_gitlab_ci/make-json.bash token=$DLSUSER_TOKEN project=$CI_PROJECT_ID branch=$CI_COMMIT_BRANCH job=$CI_JOB_ID tag=latest release=$(lsb_release -sc) > out.json
    - 'curl -X post -H "Content-Type: application/json" -d @out.json http://server-ubuntu18:9000/hooks/deploy-apt'
  dependencies:
    - build-and-test
  artifacts:
    paths:
      - build/*deb
    expire_in: 1 week  
  only:
    - master